### ISSUE TITLE
Add IceWeasel Web Browser

### ISSUE THREAD

**Issue by RetroPieNerd** [zerojay/RetroPie-Extra#102]
Can you add my script to the repository when you have a chance? You can test it out if you want to...
I put it in a zip file so I can attach it to this message.
[iceweasel.zip](https://github.com/zerojay/RetroPie-Extra/files/211319/iceweasel.zip)

**Comment by RetroPieNerd** [comment]
It is a little slow on a Raspberry Pi 1/Zero but probably faster on a Raspberry Pi 2/3....

**Comment by zerojay** [comment]
Thanks.

**Comment by RetroPieNerd** [comment]
No problem...

**Comment by RetroPieNerd** [comment]
Confirmed it works better on a Raspberry Pi 2/3!
YouTube runs smooth too!
