### ISSUE TITLE
Add FreeDink: Open-source port of Dink Smallwood

### ISSUE THREAD

**Issue by RetroPieNerd** [zerojay/RetroPie-Extra#103]
Here is the webpage: http://www.gnu.org/software/freedink/

I already made a script for this so you can test it out yourself. Feel free to modify and tweak this if you wish...
[freedink.zip](https://github.com/zerojay/RetroPie-Extra/files/211402/freedink.zip)
 I attached it in the zip file above. Also, consider it being added to the repository.

**Comment by RetroPieNerd** [comment]
When I tested it out it had a flickery screen...

**Comment by zerojay** [comment]
I have added it to a testing branch. If I feel it works well enough, I'll move it to the main branch. Thanks.

**Comment by RetroPieNerd** [comment]
Sure.

**Comment by zerojay** [comment]
I do indeed see the massive amount of flicker going on. I'll see what I can do.

**Comment by RetroPieNerd** [comment]
Ok.
