### ISSUE TITLE
Check whether X server is present when installing Attract Mode

### ISSUE THREAD

**Issue by robertybob** [zerojay/RetroPie-Extra#123]
I've just installed Attract Mode using your script, however it won't run because there's no X server on my Pi. Would it be possible to alter your script so it checks for the presence of the X server and, if not found, installs it alongside the other dependencies?

**Comment by zerojay** [comment]
It should have pulled X in along with installing xinit as a dependency. I'll add xorg as a requirement as well to try to fix this.
