### ISSUE TITLE
Oricutron (oric-1/oric-atmos)

### ISSUE THREAD

**Issue by HerbFargus** [zerojay/RetroPie-Extra#126]
https://github.com/pete-gordon/oricutron

I may give this script a go if I'm feeling ambitious

**Comment by HerbFargus** [comment]
the default repo doesnt build on the pi but I found another port from chamelonpi (from years ago) that I've hosted on my repo:

https://github.com/HerbFargus/oricutron.git

I have tested it and it does build, just needs some scripting love.

If I were feeling really ambitious one of these days I might try to merge the port with the latest upstream changes. maybe.

**Comment by zerojay** [comment]
Is this good enough to merge into the master branch?

**Comment by HerbFargus** [comment]
No it needs some improvements first, sorry I should merge onto new branches for my incomplete modules

**Comment by zerojay** [comment]
No problem.

**Comment by HerbFargus** [comment]
This has been added now, I'll look into improvements in the future when I feel ambitious.

as an added bonus Rookervik has already made a theme for the default carbon theme.
