### ISSUE TITLE
[Request] OpenXcom

### ISSUE THREAD

**Issue by BenWlson** [zerojay/RetroPie-Extra#135]
This could possibly be a port worth looking into:
https://github.com/SupSuper/OpenXcom

I haven't tried compiling it on the pi yet, so this should serve as a place-holder until someone can prove or disprove its feasibility before I do.

A quick look at the documentation shows that it will need an additional dependency to be compiled from here:
https://github.com/jbeder/yaml-cpp

**Comment by zerojay** [comment]
I've compiled it successfully, but don't have the datafiles to try running the game itself yet. I believe it uses X11 and might also use OpenGL (which I now have working with glshim). Later on tonight, we'll see how this goes.

**Comment by zerojay** [comment]
https://twitter.com/zerojay/status/721819395912110080

**Comment by zerojay** [comment]
Fulfilled in https://github.com/zerojay/RetroPie-Extra/commit/769e2e622777bb6da23ef9ab5aa179a7cd688f0d
