### ISSUE TITLE
Yabause standalone

### ISSUE THREAD

**Issue by dankcushions** [zerojay/RetroPie-Extra#136]
Hi Zerojay, mentioned this on IRC a while ago :)

Instructions for this are on https://github.com/retropie/retropie-setup/wiki/saturn - it should be scriptable. Once launched you also need to change the CPU compiler to the dynarec via the GUI (maybe this can be scripted also?), but that didn't seem to improve performance so I think there's perhaps an issue here? 

Not sure if you're interested in this, and I'm not sure what potential performance we could get out of this, but I think it's worth exploring as it certainly performed better than the current lr-yabause on my pi3. Maybe if there were issues with my build, once fixed it could be nearing playable status.

**Comment by zerojay** [comment]
I'll take a shot.

**Comment by robertybob** [comment]
There have been quite a few commits lately to this emulator so would love it if you were able to get it to work (!)

**Comment by zerojay** [comment]
I got the emulator working however I'm not getting great performance out of it, so I don't expect too much yet. Seems my disk images aren't good or something. I can't get it to load any of mine for whatever reason.

**Comment by dankcushions** [comment]
it seems to be fussy on image types. I loaded mine via the gui which tells you the extensions allowed. they do take ages to load, though...

**Comment by zerojay** [comment]
At this point, Mednafen's new Saturn core might be more promising.

**Comment by zerojay** [comment]
lr-yabasanshiro is usable now on a pi 4 with good performance. Yabause itself seems to require the desktop and GTK/QT to run. I won't be doing that at this point.
