### ISSUE TITLE
Add MineTest?

### ISSUE THREAD

**Issue by andywarburton** [zerojay/RetroPie-Extra#141]
Minetest is an awesome, FREE voxel world builder like Minecraft but open source and in active development and mod-friendly. See www.minetest.net for more info. 

I believe it's available for Debian and I hear people saying there is a RPi port availble (https://www.raspberrypi.org/forums/viewtopic.php?f=35&t=15543). 

I also found a specific RPi port of MineTest (https://github.com/Megaf/MinetestPi-Raspbian) although I'm not sure where development is as the last change on this repo is 2014.

Could be a better alternative to the official Minecraft build for Pi since MS have pretty much killed that one.

Thanks!

**Comment by zerojay** [comment]
I believe that I've got it running. At this point, I am running through writing the installation script now. It will be the latest HEAD version in github, not any dead forks.

**Comment by zerojay** [comment]
Here's the deal. lrrlircht (or whatever the engine is called again) does not have OpenGL ES by default in Raspbian. Using the standard version with the burningsvideo driver and some really really conservative settings (mainly taken from here: https://github.com/minetest/minetest/pull/3979/files) resulted in something somewhat choppy but playable.

I'm unsure if I should force those settings as default or what...or if you'd even consider this useable.

You can find the script in the new unstable repo: https://github.com/zerojay/RetroPie-Extra-unstable/blob/master/scriptmodules/ports/minetest.sh

Please get back to me with your thoughts on this.

**Comment by andywarburton** [comment]
Hey, thanks - I'll try and give it a test soon and let you know how I get on!
