### ISSUE TITLE
Add Full Minecraft through experimental OpenGL Driver

### ISSUE THREAD

**Issue by RetroPieNerd** [zerojay/RetroPie-Extra#153]
Here is a tutorial: https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=137279

**Comment by RetroPieNerd** [comment]
I should be able to test this out since I got a Raspberry Pi 3 in....

**Comment by zerojay** [comment]
Will not be going forward with this as it requires full Raspbian installation as well as breaks opengl es.

**Comment by RetroPieNerd** [comment]
Ok. Sorry...
