### ISSUE TITLE
Update to BennuGD port (Streets of Rage Remake)

### ISSUE THREAD

**Issue by Charco79** [zerojay/RetroPie-Extra#155]
An update on the Streets of Rage Remake (BennuGD) port to Raspberry Pi, I have been talking to butcher over on the BennuGD forums and he has released an updated version which now adds Sormaker mod support (fan games created using the SORR engine).

Simply replace the current file with the two files contained in this package:

https://mega.nz/#!z8MxDKyJ!A7wAgGJ728t2w45PtAOkk5eLa-P9WoiaQhq7pGgrt1o

In order to get mods to work, in the "mod" folder create a new folder called "games" and add your Sormaker games here. They MUST be in lower case, otherwise they will not work. For example, a Sormaker mod (folder) named "Example Mod" will not work, but one named "example mod" will.

The author will try and sort out the issue with the game crashing when any video mode other than "Normal" is chosen in the options. Hopefully he will resolve this issue too.

Hope this helps :)

**Comment by zerojay** [comment]
Are you sure that you have the proper file here? It is 100% identical to the file I'm already using.

**Comment by zerojay** [comment]
If I don't hear back on this soon, I'll be closing this and moving on.

**Comment by Charco79** [comment]
Yeah these are the two files butcher posted on the BennuGD forums.

**Comment by zerojay** [comment]
Nothing to do here then.
