### ISSUE TITLE
Openliero (real-time worms game)

### ISSUE THREAD

**Issue by HerbFargus** [zerojay/RetroPie-Extra#156]
Might need X: 

https://github.com/albertz/openlierox

I need to look into it more.

**Comment by zerojay** [comment]
I made an attempt at this before, but that was before I had glshim working properly. I'll take another run at it sometime after my move.

**Comment by HerbFargus** [comment]
And even if things don't compile on the pi we can set x86 flags only as I run RetroPie on my Linux machine as well.

**Comment by HerbFargus** [comment]
Just for reference: http://www.openlierox.net/wiki/index.php/Compiling_OpenLieroX_on_Linux It started to compile fine for me but ran into assembly errors, likely needs some cmake changes for the rpi platform based on what I gather from [here](http://stackoverflow.com/questions/17126593/compile-errors-with-assembler-messages) but at least warmux works :)

**Comment by zerojay** [comment]
I believe that the game is written specifically for x86 platforms so I'm not sure we'll be able to get this running. Pretty sure no distro for ARM out there has a package for this.

**Comment by HerbFargus** [comment]
Yeah probably so. At least warmux works, that's good enough for me
