### ISSUE TITLE
Hurrican (turrican port)

### ISSUE THREAD

**Issue by HerbFargus** [zerojay/RetroPie-Extra#157]
Referenced from this thread: 

https://retropie.org.uk/forum/topic/503/hurrican-turrican-clone/9

https://www.phoronix.com/forums/forum/software/linux-gaming/29540-hurrican-sdl-port?69804-Hurrican-SDL-Port=

**Comment by zerojay** [comment]
Failed miserably when I attempted last week. I'll try again.

**Comment by zerojay** [comment]
Got something that works. 640x480 only. Working on RPI version of the install script now.

**Comment by zerojay** [comment]
Completed in https://github.com/zerojay/RetroPie-Extra/pull/165. Please test it for x86.

**Comment by HerbFargus** [comment]
x86 works fine
