### ISSUE TITLE
Unable to install, hardcoded paths

### ISSUE THREAD

**Issue by aikoncwd** [zerojay/RetroPie-Extra#159]
Hi

I can't install this script, here is the error:

> cp: target ‘/home/pi/RetroPie-Setup/scriptmodules/ports/’ is not a directory
> cp: target ‘/home/pi/RetroPie-Setup/scriptmodules/emulators’ is not a directory
> cp: target ‘/home/pi/RetroPie-Setup/scriptmodules/supplementary’ is not a directory

I have Raspbian Jessie Lite installed, then I deleted user pi and I'm using all the system under root account. This scripts searchs for "/home/pi" and in my system, home directory is "/root"

Thanks!

**Comment by aikoncwd** [comment]
#160 Solved here!

**Comment by zerojay** [comment]
Breaks installation for everyone using a standard installation of RetroPie as the script needs to be run as root, which then means that $HOME returns as /root which is NOT /home/pi. As said in #160, this won't be merged.

**Comment by BenWlson** [comment]
Just an idea: if the install-extra.sh was called from within RetroPie-Setup like another port script, $home should work correctly, because lots of retropie scripts use that. Nothing in Retropie should have hard-coded paths.

**Comment by zerojay** [comment]
If this script somehow makes its way into RetroPie, I'll revisit this.
