### ISSUE TITLE
Updates scripts

### ISSUE THREAD

**Issue by RetroPieNerd** [zerojay/RetroPie-Extra#171]
The scripts need to be updated for the rewrite of the RetroPie setup script.

Original Pull request: https://github.com/RetroPie/RetroPie-Setup/pull/1489

**Comment by zerojay** [comment]
I will try to get to this soon however I am in the middle of E3 crunch time
so it may be a bit before I have time.

**Comment by RetroPieNerd** [comment]
Thanks!
