### ISSUE TITLE
Gamemaker module says "Package Help" when trying to install it.

### ISSUE THREAD

**Issue by RetroPieNerd** [zerojay/RetroPie-Extra#174]
The Gamemaker module only shows "Package Help" when trying to install it on the updated RetroPie setup script.

**Comment by zerojay** [comment]
I've confirmed the issue. Taking a look at it.

**Comment by RetroPieNerd** [comment]
Alright. :)

**Comment by RetroPieNerd** [comment]
I think I have fixed it.
Check it out: https://github.com/zerojay/RetroPie-Extra/pull/178

**Comment by zerojay** [comment]
I've had no time to work on this yet. Hopefully soon.

**Comment by RetroPieNerd** [comment]
Okay, thanks for checking in! :)

**Comment by saitoh00** [comment]
I wait for play Maldita Castilla in Raspberry, i subscribe to any change in this script

**Comment by RetroPieNerd** [comment]
Okay, thanks but it's probably going to take a while as zerojay has not given any updates in about a month. Cheers.

**Comment by hiulit** [comment]
Hey @saitoh00 ,

If you want to play **Maldita Castilla** you can follow these instructions https://github.com/bite-your-idols/gamemaker-retropie

It's more manual, but it worked for me :)

**Comment by RetroPieNerd** [comment]
I may have figured it out...
[Go test this out if you want...](https://github.com/zerojay/RetroPie-Extra/pull/181)
