### ISSUE TITLE
Enhancement: Basic video player

### ISSUE THREAD

**Issue by dult** [zerojay/RetroPie-Extra#176]
It would be insteresting if there was a direct way to launch videos from the retropie's emulation station, without having to go through Kodi.
Someone already did this: https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=130294; but it would be nice to have it as a basic extra with keyboard/gamepad functionality.

**Comment by zerojay** [comment]
I have no time for this personally, sorry. Send me a pull request and I'll integrate it.

**Comment by zerojay** [comment]
Looks like this can be done with oxmplayer. I'll give it a shot soonish.

**Comment by zerojay** [comment]
I added a script for mpv and I use it exactly as you suggested with all my games and movies in EmulationStation. Joystick support only arrived in the version after the one here so I may take another crack at this in the future.
