### ISSUE TITLE
Hurrican - Does not save Controller Preferences

### ISSUE THREAD

**Issue by PanosPl** [zerojay/RetroPie-Extra#185]
Great job zerojay!

One little thing. Hurrican does not save its Controller Preferences so everytime you must go through and re-set the Gamepad config

**Comment by zerojay** [comment]
Tell me what file it writes that info out to and I'll see what I can do.

**Comment by pelztier3011** [comment]
save game and highscoure entry suhtdown hurrican on rpi :,(

**Comment by PanosPl** [comment]
Unfortunately once I try to issue a highcore, the game crashes (pi3)

**Comment by pelztier3011** [comment]
sudo chown -R pi:pi /opt/retropie/ports/hurrican
and 
sudo chmod 775 -R /opt/retropie/ports/hurrican
than a pi reboot and highscore can be save. =)
now the config can save too.
greatings from germany

**Comment by PanosPl** [comment]
pelztier you r an ace! Thank you!!

**Comment by zerojay** [comment]
If you guys can figure out exactly what file is causing this issue, I can fix the script.

**Comment by pelztier3011** [comment]
i think this 2 files need writable:
/opt/retropie/ports/hurrican/Hurrican.hsl -> highscoure.
/opt/retropie/ports/hurrican/Game_Log.txt -> log + language i thing.

**Comment by zerojay** [comment]
There's also a Hurrican.cfg that needs to be touched and writable but even with that change (and seeing the game say it can write to it), the control changes are not saved regardless. I'll be submitting some fixes for this script shortly.

**Comment by zerojay** [comment]
Give this a shot and reopen if you run into any issues and I'll take another look.
