### ISSUE TITLE
libsdl-mixer1.2 nneded for SoRR

### ISSUE THREAD

**Issue by biscuits99** [zerojay/RetroPie-Extra#186]
As mentioned here:
https://retropie.org.uk/forum/topic/3432/is-streets-of-rage-remake-working-for-anyone-in-4-0/12

It looks like libsdl-mixer1.2 is needed for SoRR to work?

**Comment by zerojay** [comment]
Should be fixed in https://github.com/zerojay/RetroPie-Extra/commit/0c56ac9f02ef592a40cf1625cb84170f0ed48205.

Thank you.
