### ISSUE TITLE
Add AM2R port

### ISSUE THREAD

**Issue by hiulit** [zerojay/RetroPie-Extra#189]
Could it be possible to add this game?

**Comment by zerojay** [comment]
Try it and then send me a pull request. Otherwise, I'm not really doing work on RetroPie anymore as I'm far too busy.

**Comment by RetroPieNerd** [comment]
Nope. Not enough RAM...
I already attempted port this [just like I did with Undertale](https://retropie.org.uk/forum/topic/2704/undertale-for-retropie-raspberry-pi), but same result...
