### ISSUE TITLE
Mayhem

### ISSUE THREAD

**Issue by afiction** [zerojay/RetroPie-Extra#190]
Hi. Great work. I'm having trouble with Mayhem though. It says "'sfx_boom.WAV'" not found and it doesn't pop up in the Ports section after installation. I'm running the latest version of RetroPie.

**Comment by zerojay** [comment]
The file system is case-sensitive so see if you have a sfx_boom.wav or similar and rename it to match the requested casing.

**Comment by zerojay** [comment]
No response, closing.
