### ISSUE TITLE
Can't save in SoRR

### ISSUE THREAD

**Issue by Dochartaigh** [zerojay/RetroPie-Extra#191]
Hope this is the right place to post this - I'm running RetroPie 4.1 on a Raspberry Pi 3. Have SoRR (Streets of Rage Remake) up and running but I can't for the life of me figure out how to save, and load a save game. I have a random save game created at the very first scene....which the game boots into automatically when I launch it from RetroPie's Ports menu, but that's it...and I don't know how that save got there.

Can you please tell me:

1.) How to save? 
2.) How to restore a save game? 
3.) Is there only 1 save game slot? 
4.) Can you save at any point? 

I was told on a PC you hit F12 to save, which I tried on my Raspberry Pi's keyboard (two of them), but that just exits out of the program (which is good to know because the normal hotkeys of Select+Save or Esc to exit don't work in SoRR!). Thanks!

**Comment by zerojay** [comment]
As far as I'm aware, the game saves on its own. I'm able to see my control changes are saved when I quit with F12. I don't have any of the other info you're looking for, sorry.
