### ISSUE TITLE
GameMaker games don't boot

### ISSUE THREAD

**Issue by hiulit** [zerojay/RetroPie-Extra#193]
I have the latest version of Retropie (4.1).
I've installed Retropie-Extra and installed the GameMaker package from the experimental section in Retropie and they just don't boot, at all :(

Is there something else that we have to do? A part from installing? Maybe permissions?

**Comment by hiulit** [comment]
OK, I think I found the problem.
When I tried to launch `MalditaCastilla` directly from the command line I got this error

```
./MalditaCastilla: error while loading shared libraries: libopenal.so.1: cannot open shared object file: No such file or directory
```

So I installed `libopenal-dev` with:

```
sudo apt-get install libopenal-dev
```

And it's working!

Maybe, since this dependency seems mandatory for Maldita Castilla to run, it could be added in the GameMaker's games installation script?

**Comment by hiulit** [comment]
I submited a pull request https://github.com/zerojay/RetroPie-Extra/pull/195

**Comment by zerojay** [comment]
I've accepted the pull request, thank you. Reopen if this isn't working properly.
