### ISSUE TITLE
Chromium: Cannot open /dev/tty0 (Permission denied)

### ISSUE THREAD

**Issue by kmudrick** [zerojay/RetroPie-Extra#196]
I installed chromium, but unfortunately it will not launch due to x errors.  I am not sure what is causing this (note: I ran `dpkg-reconfigure x11-common` and allowed "anybody" to run x)

From `/home/pi/.local/share/xorg/Xorg.0.log`:

```
[    45.528] (EE)
Fatal server error:
[    45.528] (EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
[    45.528] (EE)
[    45.528] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[    45.528] (EE) Please also check the log file at "/home/pi/.local/share/xorg/Xorg.0.log" for additional information.
[    45.528] (EE)
[    45.529] (WW) xf86CloseConsole: KDSETMODE failed: Bad file descriptor
[    45.529] (WW) xf86CloseConsole: VT_GETMODE failed: Bad file descriptor
[    45.547] (EE) Server terminated with error (1). Closing log file.
```

**Comment by zerojay** [comment]
I've updated the script to install the proper package as the XWrapper stuff has moved to xserver-xorg-legacy. You should now be able to apt-get xserver-xorg-legacy and then run dpkg-reconfigure xserver-xorg-legacy, select "anybody" and then run it.

**Comment by zerojay** [comment]
Any luck? I've updated the version installed recently so try reinstalling it.

**Comment by zerojay** [comment]
No response received, closing.

**Comment by pgmillon** [comment]
Hi,
I had the very same issue when trying to start chromium on my Pi4B.
Running your recommanded steps worked like a charm.

**Comment by zerojay** [comment]
I'm having a weird issue with this as it seems xserver-xorg-legacy will get randomly removed during apt installs for whatever reason.

**Comment by yulrizka** [comment]
Just bumped into this issue
After running
```
$ sudo apt-get install xserver-xorg-legacy 
$ run dpkg-reconfigure xserver-xorg-legacy

select "anybody" 
```
Solves the issue for me
