### ISSUE TITLE
Chromium Crashing to Emulation Station

### ISSUE THREAD

**Issue by LiqwdE** [zerojay/RetroPie-Extra#199]
Installed from repository. Rebooted system. Chromium opens to black screen and crashes to Emulation Station. Tried the dpkg-reconfigure for x11. Saved and rebooted, Chromium still Crashing.

Upon install from Retropie Setup, I received no warnings from Chromium.

If i f4 to console, I can manually start with - startx chromium-brower
But will not launch from Emulation Station

Advice?

Edited: IceWeasel is doing the same thing.

**Comment by zerojay** [comment]
Take a look at what shows up in /dev/shm/runcommand.log and let me know.

**Comment by zerojay** [comment]
Also the version of Chromium installed has changed so try reinstalling as well. It worked for me.

**Comment by zerojay** [comment]
No response received, closing.
