### ISSUE TITLE
Chocolate Doom does not build

### ISSUE THREAD

**Issue by dudleydes** [zerojay/RetroPie-Extra#201]
Chocolate Doom does not build because the default branch for the Github repo is now sdl2-branch. Here is the build log: http://pastebin.com/NbwWrk61.

Chocolate Doom seems to build fine from the master branch. Not sure what the best approach is - to add SDL2 dependencies or force the master branch in the scriptmodule.

**Comment by zerojay** [comment]
I would change to the master branch and make sure the dependencies are proper for it.

I can't do this myself as my Pi died a few days ago.

**Comment by dudleydes** [comment]
The master branch builds fine if I do it manually by downloading the zip. If I change the sources section of the module to

````
function sources_chocolate-doom() {
    gitPullOrClone "$md_build" https://github.com/chocolate-doom/chocolate-doom.git "master"
} 
````

then I get the same build error.

According to the [Chocolate Doom wiki](https://www.chocolate-doom.org/wiki/index.php?title=Raspberry_Pi&amp%3Bdiff=2147&amp%3Boldid=1618), 

> The SDL2 branch of Chocolate Doom (future v3) works quite well on the Raspberry Pi in DirectFB mode (not under X), but requires a special version of the SDL2 libraries that are available from the Retro Pie project. 

If you could let me know what the SDL2 dependencies should be, I can amend the scriptmodule and test.

**Comment by zerojay** [comment]
The SDL2 dependencies were fixed by a previous commit. I also updated the libpng-dev dependency to libpng12-dev to avoid a problem. I was able to compile the master branch and run it just fine now. Sorry for the wait.
