### ISSUE TITLE
SuperTuxKart not going fullscreen

### ISSUE THREAD

**Issue by cbix** [zerojay/RetroPie-Extra#204]
I'm running RetroPie on a Pi 3 and Pi 2 with a Full HD screen and managed to install and launch supertuxkart after changing the X permissionsto "Anyone". Unfortunately though, the supertuxkart preferences only provide resolutions up to 1024x768 and its view is placed in the bottom left corner of the screen.

Output of `xrandr`:

    Screen 0: minimum 1280 x 720, current 1280 x 720, maximum 1280 x 720
    default connected 1280x720+0+0 0mm x 0mm
       1280x720       0.00*

**Comment by zerojay** [comment]
I'm getting full screen by default however I am getting an error about the GPU being too old and the game crashing when you select your profile.

**Comment by zerojay** [comment]
Full screen and full resolution is now possible but it performs way too slowly, moved to unstable.
