### ISSUE TITLE
SuperTuxKart not opening (RetroPie 4.2)

### ISSUE THREAD

**Issue by Allanbuzzy** [zerojay/RetroPie-Extra#207]
I have installed the .sh file and put it in my ports folder, the problem is that the game doesn't load when I try to play it. I select it, black screen, booted back to the Ports menu. How do I fix this and why is it not loading?

**Comment by zerojay** [comment]
Did you do a source or binary installation? I just attempted a binary install and found that it misses the glshim required to play which I believe should be installed with the source install.

**Comment by zerojay** [comment]
With a source install, I can confirm that I see the same behavior as you are. Looking into this.

**Comment by zerojay** [comment]
Should be fixed in #216.
