### ISSUE TITLE
Heboris is impossible to close with only a controller

### ISSUE THREAD

**Issue by AratnitY** [zerojay/RetroPie-Extra#208]
As fun as having a TGM-styled game on the pi is, I can't get much use out of it due to the game requiring the escape key to be pressed to close it. (I don't keep a keyboard attached to my pi)

I tried adding in a quit option in the test menu (line 14908, in the gist link below), however I'm running into multiple depreciation errors when trying to compile it so I can't really test if it actually works. (See here: http://i.imgur.com/Vk0nTQK.png )

This is the attempt at code that I threw together that may or may not actually work:
https://gist.github.com/AratnitY/d64d128baf94505f0c1cc5b9fba87ccb

Do you think this is something that could be added in?

**Comment by zerojay** [comment]
The deprecation errors you're talking about in your logs are just warnings. They shouldn't cause compilation to fail. I'll take a look at it sometime this weekend. To be honest, I'm not sure there's anything I can do about it but we'll take a look at your code and see what happens. I appreciate you taking a swing at it.

**Comment by zerojay** [comment]
Question for you: Did you add anything else other than the menu item? Wouldn't there need to be logic to actually go through with quitting the game?

**Comment by zerojay** [comment]
Upon deeper inspection, the game is expecting a keyboard to exist as there are more commands that require keyboard use than just quitting. My advice to you is to use something like xboxdrv to map the ESC key to one of your controller keys. If you decide to send me a pull request with joystick support added, I'll accept it but I feel like fixing this is something beyond the scope of this repo.
