### ISSUE TITLE
EasyRPG Player doesn't start

### ISSUE THREAD

**Issue by TheFireRed** [zerojay/RetroPie-Extra#210]
After installing this package, I followed these steps: https://github.com/zerojay/RetroPie-Extra/wiki/EasyRPG-Player

The application doesn't start. It just goes back to Emulation Station. I have a Raspberry Pi 3 B.

**Comment by zerojay** [comment]
Going to be taking a look at this shortly once my current Retropie install is backed up properly. Hopefully have an answer for you on this today.

**Comment by TheFireRed** [comment]
Thanks!

2017-07-22 18:43 GMT+02:00 zerojay <notifications@github.com>:

**Comment by zerojay** [comment]
I did a fresh install and had no problems running Taut as found on that page. One thing that might be confusing is that the original instructions didn't really mention the RTP files you need to copy and where you find them from so I clarified that a little bit. Give it another shot and let me know how it goes.

https://github.com/zerojay/RetroPie-Extra/wiki/EasyRPG-Player
