### ISSUE TITLE
Additional games

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#212]
Hello, i have tested and successfully added some more games to the retropie ports by manual adding shortcuts to the ports menu the games are:

lgeneral
lmarbles
lbreakout2
simutrans
tuxpuck
tower toppler (toppler)
freecraft
OpenArena

They all working fine can you add them to the extras/experimental menu please?

**Comment by zerojay** [comment]
Send me a pull request with your installation scripts.

**Comment by symbios24** [comment]
I don`t really know how to use the pull request all i did was that:

sudo apt get install lgeneral lmarbles lbreakout2 simutrans tuxpuck toppler freecraft openrena 

After i created folders with the scripts in the ports folder of retropie home/pi/retropie/ports
eg: a simutrans folder with a script start.sh inside the contents of the script are only the name of the game "simutrans" and the game shows in retropie in the port section like this, and also i make the script executable with the chmod command.

for the openarena the process was a little different:

sudo apt-get install openarena
wget http://www.berryterminal.com/dl/ioquake3_99.1.36-rpi01_armhf.deb
sudo dpkg -i ./ioquake3_99.1.36-rpi01_armhf.deb

And i created a folder "openarena" in the ports as normal and a Start.sh script inside with the command: 

#!/bin/bash
sudo /usr/games/openarena

and of course make the script executable

That`s all i did for the 8 games i hope you can add them

ps i also installed the sound pack for freeciv since the game does not have it by default 
sudo apt-get install freeciv-sound 

i will appreciate if you can add all this to your extra scripts.

Thank you
