### ISSUE TITLE
Instructions/problems

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#218]
Hello, i want to install some of the games/ports below from your script but i cannot find any instructions about where i put the game files and what game/versions specific needed for them to work

where to put game files:

freesynd.sh - Syndicate clone
openxcom.sh

-----------------------------

Not working

mayhem.sh does not work
roadfighter.sh does not work

---------------
misc problems

corsixth.sh - Theme Hospital after first run it shows a very tiny screen in the left that shows graphic artifacts/glitches and needs to specify the game folder so it can load impossible to do anything in there.

Hurrican turrican clone plays in a very small screen/resolution in the middle

**Comment by zerojay** [comment]
Usually the modules themselves tell you where you should put the data files if you open them up. Retropie recently added package help tags (which changed from the old way of doing things) so I'll be adding them to make things more clear.

Hurrican already has a new style package help tag to tell you what you need to do to fix your resolution problem. I'll be updating that package soon to hopefully fix some permissions issues.

For the future, each of these should be separate bugs because I could fix a few of these and have one that won't be fixed and... well, what do I mark the entire thing as at that point?

**Comment by zerojay** [comment]
The Corsixth script also already has the new package help detailing everything you need to fix that issue as well.

**Comment by zerojay** [comment]
Does "does not work" mean you were able to install roadfighter and mayhem but they don't run or...? I had some install issues, but you don't specify.

**Comment by symbios24** [comment]
Thanks i need to install the freesynd.sh openxcom.sh but i don`t really know were to put the files or what fgame version is needed

Any change to put to the script the games i mention before?
lgeneral
lmarbles
lbreakout2
simutrans
tuxpuck
tower toppler (toppler)
freecraft
OpenArena

**Comment by zerojay** [comment]
I don't know why you've put a list of games below, I don't think I have them in my repository.

I'm looking through your issues one by one and working on them now. I'll update the repository and close this issue when that's done. I'm currently looking through Mayhem which changed some of it's dependencies recently (allegro4.4 -> allegro5.0).

**Comment by symbios24** [comment]
I installed and tested this games manual and they work great,so i said maybe you can add them to your script.

also burgerspace.sh  /  crack-attack.sh and maelstrom.sh are not working

Thanks a lot

**Comment by zerojay** [comment]
As I said above, I need more info than just "not working".

**Comment by symbios24** [comment]
i installed them and they are not running they return me to emulation station.

**Comment by zerojay** [comment]
So they successfully install and just fail to run?

**Comment by zerojay** [comment]
I've updated the mayhem script for new dependencies however it won't run. I've contacted the author over at https://github.com/martinohanlon/mayhem-pi/issues/29. On to the next one.

**Comment by symbios24** [comment]
They all successfully installed 
crack attack can be installed only from source 
maelstrom now runs must be an update i did from retropie or from another game that fixed this

**Comment by zerojay** [comment]
Everything should be installed from source. I'm not sure why there would be an install from binary.

**Comment by symbios24** [comment]
most of the games/ports have only binary install

**Comment by zerojay** [comment]
Give Roadfighter another shot. Should work now.

**Comment by zerojay** [comment]
Updated Freeciv to include freeciv-sound-standard.

**Comment by zerojay** [comment]
Burgerspace is provided by Raspbian and is installed through binaries. If you have not allowed X to be run by other users, you get a black screen. See the troubleshooting section of the readme. I'll be adding the required package to allow it and help mentioning it to the module shortly.

**Comment by zerojay** [comment]
Burgerspace module updated.

**Comment by symbios24** [comment]
freesynd.sh  does not have anything in help on where to put the game files,thanks for the making

**Comment by zerojay** [comment]
Crack-Attack has a GTK interface that lets you select your options but is a pain in the ass to deal with. I've added help for the module there but you will still see a console window overlaid for the moment. I'll have to figure that out a bit later.

**Comment by symbios24** [comment]
no worries about crack attack,

**Comment by symbios24** [comment]
i found the location of openxcom its in /media/retropie/opt/retropie/ports/openxcom/share/openxcom
can you add the location in the help?

also the freesynd location is in /media/retropie/opt/retropie/ports/freesynd
but it does not play it returns me in emulation station

**Comment by zerojay** [comment]
Updated openxcom with more info.

**Comment by zerojay** [comment]
Maelstrom is working fine for me.

**Comment by symbios24** [comment]
its working for me too,only syndicate is not working

**Comment by zerojay** [comment]
Added more information about Corsixth that should help you get it up and running.

**Comment by symbios24** [comment]
thanks again talk you tomorrow for further info gotta sleep now

**Comment by symbios24** [comment]
good morning

**Comment by symbios24** [comment]
I found it, it plays great, the folder in /home/pi/retropie/roms/ports/freesynd is where the game files going can you correct it in help?

**Comment by zerojay** [comment]
Please file these as separate issues for tracking, thanks.
