### ISSUE TITLE
Kweb needs dependency xterm

### ISSUE THREAD

**Issue by dkoppenh** [zerojay/RetroPie-Extra#234]
I installed the kweb package, but it failed to run because xterm wasn't installed. I added xterm to the getDepends line to solve the problem.

**Comment by zerojay** [comment]
lxterminal is already one of the dependencies. Why would we need to install a second terminal? Does lxterminal not run for you?

**Comment by dkoppenh** [comment]
X didn't start until I installed xterm.  Sorry I don't have time to dig for a log of the failed run command ATM.

**Comment by zerojay** [comment]
Should be fixed. Please reopen if it doesn't work for you.
