### ISSUE TITLE
Please not use cmake in manalus package

### ISSUE THREAD

**Issue by 4144** [zerojay/RetroPie-Extra#237]
Cmake build system is legacy in manaplus, and may works not effective.
It missing all flags, and can works only with SDL 1.2.
Better use automake/autoconf. It allow use SDL1.2 or SDL2, and select different other libs

https://github.com/zerojay/RetroPie-Extra/blob/428ec9690f51421730ba51ba5b36a3d12541f628/scriptmodules/ports/manaplus.sh#L27

**Comment by symbios24** [comment]
it seems the creator is out for vacations he is not answering anything.

**Comment by zerojay** [comment]
Sorry, my pi's memory card died and I've been swamped at work. I'll get to
this shortly.

**Comment by zerojay** [comment]
I'd also accept a pull request for the change.

**Comment by zerojay** [comment]
Should now be fixed.
