### ISSUE TITLE
Updating Script

### ISSUE THREAD

**Issue by robklingler** [zerojay/RetroPie-Extra#243]
Suggested enhancements for your consideration...

1) Add instructions in the Read Me file for how to update to the latest script if you've installed an earlier script.  I presume this involves going into the RetroPie-Extras directory and running "git pull origin" but if you've got a preferred approach, I'd love to know about it.

2)  If feasible, consider adding an entry in RetroPie Setup itself for RetroPie Extras, allowing users to update from within the RetroPie interface (just like we would update any other element of RetroPie).

**Comment by zerojay** [comment]
Great ideas. I'll see what I can do.

**Comment by zerojay** [comment]
Would be nice if we had some help on this one.

**Comment by PokeEngineer** [comment]
@zerojay 

I'll try to set aside some time and I will see what I can do.

**Comment by robklingler** [comment]
Not sure how much help I can provide... don't really understand linux scripting or github, but I generally can write decently, so I should at least be able to help on the readme/instructions.  I'll do what I can.

**Comment by zerojay** [comment]
If someone figures out a way to do this, reopen.
