### ISSUE TITLE
SORR Is it a way to make SorMaker working

### ISSUE THREAD

**Issue by Darknior** [zerojay/RetroPie-Extra#245]
SORR working perfectly on PI3 with PAD !
Really excellent, but when i unlock SorMaker and try with it to launch MODs it exit the game to ES.
Is some one already have play a mod on this engine. I have make a good collection with best of them with this engine on my xBox and i'm so sad to not use them.
Thanks

**Comment by zerojay** [comment]
Try following these instructions. I'm pretty sure the engine version I'm using is already the one posted on that page so SORMaker *should* work.

**Comment by Darknior** [comment]
Thanks, you make me discover Bennu today lol ... the engine used to make SORR, i always think they made it from scratch.

- I try again MAKER, and after choose a player 2 or AI it take me out.
I can't see the screen where i can choose the games i have add. On xBox it works perfectly, and i use my mods made for xbox set. Like on the video 👍 

![sans titre-1](https://user-images.githubusercontent.com/3703317/32947291-7776ba66-cb9b-11e7-8915-351156cb45dc.jpg)

https://youtu.be/9I6lQGoRmS8?t=32s

- On the exemple it use the 333 last PI version of the engine, but i read it is not better, same crash when we want to change resolution. We must play in normal mode.

- The PSP option can be cool to write in doc when we install the game, i already read it on the forum, but i don't like it because we have the EXIT button but we lost the player two :(
So bad we can't have the EXIT button and 2Player at same time :(

- From years i also have the hacked savegame to unlock all the characters and weapons and levels ...
Maybe you can add it to the package, renamed, and if some one want to use it it can rename it.

[savegame.sor.zip](https://github.com/zerojay/RetroPie-Extra/files/1482195/savegame.sor.zip)

**Comment by zerojay** [comment]
I recently upgraded the engine version of the port to install version 333. I forgot to test this, so I grabbed your hacked savegame file and installed it and SorMaker functions now! I was able to play through the default prototype mod. Would love to know where to find more.
