### ISSUE TITLE
Zelda Picross not working

### ISSUE THREAD

**Issue by Darknior** [zerojay/RetroPie-Extra#248]
I try it yesterday and it freeze when you are on the Vincent Rouille screen.
You can only make ESC to quit.

Nothing in the LOG because the game starting ...

`zeldapicross
zeldapicross

SDL_VIDEO_EGL_DRIVER=/opt/vc/lib/libEGL.so SDL_VIDEO_GL_DRIVER=/opt/vc/lib/libGLESv2.so pushd /opt/retropie/ports/zeldapicross; /opt/retropie/ports/zeldapicross/Zelda-Picross; popd
`

For information Zelda Navi's Quest working fine for me.
But only on Keyboard because no Joypad configuration in game.
And it is really slow when an ennemi come on the screen. I don't know if it is possible to fix buy a different compilation option ?

**Comment by Darknior** [comment]
> @Vincent : As for the problem of the game that blocks, there was a problem on my first games, mainly on the laptop keyboard, where it was necessary to disable the keypad for the key input is well taken into account. Maybe you have a problem of this kind?

I think it's my problem. Maybe you can notice it at the install end.

http://www.zeldaroth.fr/forum/viewtopic.php?t=2780

**Comment by zerojay** [comment]
I remember just hitting a key on the keyboard to advance. Maybe Enter.

Bugs with other ports should be in their own issues.

**Comment by zerojay** [comment]
By the way, Zelda3t is in the RetroPie-Extra-unstable repo. It compiles but has graphical glitches all over which is why it isn't in my main repo.

**Comment by Darknior** [comment]
Ok thanks i will go to see this unstable branch i don't see before.
