### ISSUE TITLE
Zelda 3T and OLB working with glitch

### ISSUE THREAD

**Issue by Darknior** [zerojay/RetroPie-Extra#249]
I have test the two games, finally easy to compile.
The two games works fine but with graphical glitch.

Zelda 3T has graphical glitch, is only in French and with text problems.
Zelda OLB has same problems + No Music !

But it is better than Zelda NSQ that have graphical problem + slow down. Maybe because this one is in 60Hz!

I have made some test and videos, i will try to see if Vincent can help us to fix it.
http://www.zeldaroth.fr/forum/viewtopic.php?p=45237#45237

**Comment by zerojay** [comment]
Could be. I also have my pi overclocked so I might be seeing less issues because of it.

**Comment by Darknior** [comment]
Do you think overclock add issues ?
I wish Vincent will answer me. To stand they come to SOLARUS. OLB will come in April 2018.
And a guy began to port Navi's Quest, i will try it too.
https://github.com/syllan/zelda-nsq-se

**Comment by Darknior** [comment]
Found the sound (music) solution, we must install **timidity** and it's rock.

`apt-get install timidity`

You must add it to the install script to read midi files on Linux.

**Comment by zerojay** [comment]
I don't know what this is referring to. I don't see you say anything about a sound problem before and I don't know which game you are talking about needing it?

**Comment by Darknior** [comment]
The two Zelda games, 3T and OLB, with real official site source code, no GIT non official work with glitch.
They use MIDI music, and it doesn't work fine without timidity.
There are important because there are the sequel of the **Zelda Return of the Hylian** but they are not already ported to SOLARUS. It will take some years ...
Zelda Oni Link Begins - OLB will come on SOLARUS for 2018-05 if not in late ...

OLB FR : http://www.zeldaroth.fr/fichier/OLB/linux/ZeldaOLB-src-linux.zip
3T FR : http://www.zeldaroth.fr/fichier/3T/linux/Zelda3T-src-linux.zip

OLB US : http://www.zeldaroth.fr/us/files/OLB/Linux/ZeldaOLB_US-src-linux.zip
3T US : http://www.zeldaroth.fr/us/files/3T/Linux/Zelda3T_US-src-linux.zip

It's bad because i don't think it's was possible to choose LANGAGE on the Retropi-Setup / Extra ?
If not you must add 4 install scripts. The only different file was the **text.cpp**
If you can share the text here, only one game DL link is enough, i'm working on the french one to fix UTF-8 problem on our Retropie linux.

The .SH from source file i began last week.

[zelda3t-olb.zip](https://github.com/zerojay/RetroPie-Extra/files/1490633/zelda3t-olb.zip)

-----------------------------------------------------------------------------------------------------------------

The new one NSQ has no sound problem, and it's the same version for US and FR because it is a new engine : 

http://www.zeldaroth.fr/fichier/NSQ/linux/ZeldaNSQ-src-linux.zip

**Comment by zerojay** [comment]
I'll try taking a look at this sometime soon.

**Comment by zerojay** [comment]
Solarus is in RetroPie itself now.
