### ISSUE TITLE
Rockbot 1 and 2 on PI - NEW ADD

### ISSUE THREAD

**Issue by Darknior** [zerojay/RetroPie-Extra#250]
I have try to compile Rockbot on PI :)
And now i have understand that's an engine to make Megaman games and not an only one game lol

http://rockbot.upperland.net/?page_id=301

It take me some time because i must install QMAKE and understand what is it, and how to use it.
I have choose the version 5, and it works fine.

[code]apt-get install qt5-default
apt-get install qtcreator[/code]

I take Rockbot on the GIT

`git clone --recursive https://github.com/protoman/rockbot`

```
qmake -makefile .
make
```

Move the EXE file in build dir, launch and it works very fine :)
I have a bug at start but it was because the game was not in full screen, and the image flick very fast.
Now we have Rockbot 1 n 2 on PI :)

https://photos.app.goo.gl/MgxePe5VOQlyijXi2
In NOT in Full screen, this bug :
https://photos.app.goo.gl/M1NVMJ1Y0jPQQncn1

-------------------------------------------------------------------------------------------------------------------

I think you can add it her, it is really a cool engine :)
But two things to made : 

- Copy two times the build dir on PI with the EXE file and separate the two games. It is better to use, and Rockbot 1 is finished 100%, i'm not sure for Rockbot 2.

- Configure game in FULL SCREEN to fix video problem, but i don't found where it put the save file ???

**Comment by Darknior** [comment]
You can remove or not copy two directories by game to save place :

build/packages
build/template

**Comment by Darknior** [comment]
Ok perfect :)
Don't forgot to split them and config them in full screen or it will flick on TV and every one will tell you that game s are not working fine.

**Comment by zerojay** [comment]
I'm not splitting them as there's no need to do so. I don't see a way to configure them to the proper settings by default but I put a warning in the package help about it.

**Comment by zerojay** [comment]
I think I'll just edit the source so that it is correct by default.

**Comment by Darknior** [comment]
Yes good idea to edit source :)
I write to separate because it is two games, it's cool to have two entry in ES. Command line not working when i try. And the two games already have days updates ...

https://www.youtube.com/watch?v=o6QLhYU605s

I make this for me this week many work on MEDIA with Photoshop, i ha two Rockman.

I'm working a lot on other games i will post some other Pull Request when done.
