### ISSUE TITLE
Solarus & Zelda fangames

### ISSUE THREAD

**Issue by Darknior** [zerojay/RetroPie-Extra#254]
There is already a script in **Retropie-Setup** to install **Solarus**, but from files, not GIT source code, and it's outdated. Solaris v1.4.5

I have work on it, and compile **five** Solarus games, and modify them to fix the Analogic pad problem, and the hability to exit game to ES with the Menu, with controller, and not ESC on Keyboard.
These function will be add in the future on the official release, but not immediately.

Maybe i can upload my files and we can make them install from bin.

Using GIT source is possible too but will take most work because you must patch some files.

These Zelda are really fantastic. Now with Solarus 1.5.3 or Dev 1.6.0
An some new games come ...

I f you want to work on them to add them for every one, i can help you and give my compiled files.

Solarus
git clone --recursive https://github.com/solarus-games/solarus.git

Zelda Book of Mudora ZBOM 1.3.1 - Solarus 1.5 (-quest-size=640x480) (Partiel FR sur le GIT)
https://sites.google.com/site/zeldabom/download
git clone --recursive https://github.com/wrightmat/zbom.git

Zelda Return of the Hylian ROTH SE 1.2 - Solarus 1.6 (320x240)
git clone --recursive https://github.com/solarus-games/zelda-roth-se.git

Zelda Mystery of Solarus ZSDX 1.12 - Solarus 1.6 (400x240)
git clone --recursive https://github.com/solarus-games/zsdx.git

Zelda Mystery of Solarus ZSXD 1.12 - Solarus 1.6 (400x240)
git clone --recursive https://github.com/solarus-games/zsxd.git

Zelda Mercuris Chess ZSXD2 1.0.4 - Solarus 1.5 (320x240)
git clone --recursive https://github.com/solarus-games/zelda-xd2-mercuris-chess.git

To launch Solarus in **16/9** there is a command line : 

`solarus-run -quest-size=400x240`

**Comment by zerojay** [comment]
I'm the one that created the original installation scripts for Solaris in Retropie. I'll probably just create an updated version that compiles from git. Put whatever info you think I'll need here and I'll tackle it when I get to it.

**Comment by Darknior** [comment]
You have all the GIT URL to take an **pack** games, The Solaris GIT to **make the master 1.5.3** version
To compile the last Solarus i have use the **-DSOLARUS_GUI=OFF** option we don't use on PI.

You put games here : **/opt/retropie/ports/solarus/share/solarus/GAMENAME/**
Please, change GAMENAME dir by a LS link **/home/pi/RetroPie/roms/ports/solarus/GAMENAME/**
Games take place on SD card, it is better to have them on ROM folder on USB device.
Like you already do for RPGMaker.

`ln -s /home/pi/RetroPie/roms/ports/solarus /opt/retropie/ports/solarus/share/solarus`

All the bash in the directory **/opt/retropie/ports/solarus/bin** are not used, only let the **_run** file.

Use this command on **emulators.cfg** for the two games 16/9 compatible.

`.../bin/solarus_run -quest-size=400x240 /opt/retropie/...`

The source code of Solarus is update every day, it's why i think using master is better, more stable.
But it is 1.53 and some games are already set to 1.6, you must edit the **quest.dat** to change the value to **1.5**

https://github.com/solarus-games/zsxd/blob/dev/data/quest.dat

For the **Analogic JOYSTICK fix,** i have Pull Request it on the Solarus Official **ZSDX** game, It must accept it and make same on the 4 games. It is ok but i don't know when he will do it. For The **Book of Mudora** i have Pull Request and he have accept today.

The only **PATCH** you must add in your **.sh installer** was the **EXIT** option with menu to works fine with **Joystick** and not with **ESC** on Keyboard.

In this file : **pause_submenu.lua**

https://github.com/solarus-games/zsxd/blob/dev/data/menus/pause_submenu.lua

Search : **sol.main.reset()**

```
     if self.save_dialog_choice == 1 then
          sol.main.reset()
        end
```

And replace it by : **sol.main.exit()**

It depend of the game, some time once or three time in the file, i replace this for Joypad function.
Like that when you quit your game, it not go to Title Screen but to ES.

If you can do all of that in SH, it will be perfect for gamer.

**Comment by zerojay** [comment]
I'll try taking a look at it soon.

**Comment by nibio74** [comment]
Thank you!

**Comment by zerojay** [comment]
Is there any point in me tackling this when it appears to be in RetroPie already?
