### ISSUE TITLE
Chromium/Firefox Browser Enhancement

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#255]
Hello i saw you start adding some of the games from the list i give you in the script thank you.
Can you include flash player plugin also to be installed by default with chromium browser and firefox-esr browser ?

Thank you

**Comment by symbios24** [comment]
If it helps the command to install flash for chrome is sudo rpi-chromium-mods for firefox i dont know it

Thank you

**Comment by zerojay** [comment]
rpi-chromium-mods is the package that needs to be installed for Chromium to play Flash, you're saying?

**Comment by symbios24** [comment]
Yes its includes flash player and an adblocker.
