### ISSUE TITLE
Input RetroPie-Setup Home

### ISSUE THREAD

**Issue by lashower** [zerojay/RetroPie-Extra#258]
I would like the install-extras.sh file to support inputted directory for /RetroPie-Setup location.

Could you change the file to something like this?

```
#!/bin/bash

RPS_HOME='/home/pi/RetroPie-Setup/'
if [ ! -z "$1" ];then
    echo $1
fi
cp -R scriptmodules/* $RP_HOME
```

**Comment by zerojay** [comment]
I'm not opposed to doing that. If you have the time, send me a pull request, otherwise sure, I'll do it but might take me some time.

**Comment by lashower** [comment]
Thanks for the quick response. I'll try to figure out how to do a pull request. This is my first time adding to a repository that isn't my own.

**Comment by zerojay** [comment]
Not a problem. Think of it as a good reason to learn. Fork my repo, make your own local changes to it and you should see a button for creating a pull request.

**Comment by lashower** [comment]
I think I finally figured it out :+1: 
Does it look good?

**Comment by zerojay** [comment]
You did it right. I reviewed it quick and asked for a change.

**Comment by zerojay** [comment]
Likely super stale. Reopen if otherwise.
