### ISSUE TITLE
Cromium problem

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#260]
Hello, chromium is crashing back to emulation station after executing from a fresh install, in the runcommand.log file it says

Executing: xinit  /opt/retropie/ports/chromium/chromium.sh -- vt1 -keeptty

/user/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error

Also the rpi-chromium-mods is not installed by default in your script you put it on dependency, i think you should put it in function sources_chromium in the line that says apt-get install chromium-browser 
eg: apt-get install chromium-browser rpi-chromium-mods

Thanks

**Comment by zerojay** [comment]
> Hello, chromium is crashing back to emulation station after executing from a fresh install

README.md and the module help has been updated to match.
