### ISSUE TITLE
Open Jazz

### ISSUE THREAD

**Issue by Darknior** [zerojay/RetroPie-Extra#262]
If you want you can add OpenJazz to the Extra.

```
git clone https://github.com/AlisterT/openjazz
make
```

I try many version, this one is the last up to date and works fine on PI with Joystick. The Only problem for the moment is we must use the ESC key to go back in Menu. And we can't map it on the Joystick. I don't know how to hard map it in source code myself.

It is a great game for sure :)

**Comment by Darknior** [comment]
An other bug, the music stop at track end :(
And not loop ... i don't know how to fix it.

**Comment by symbios24** [comment]
i think you are a little obsessed with joysticks music player with joystick doesn't match

**Comment by symbios24** [comment]
the joystick man!!!

**Comment by Darknior** [comment]
I have a friend that work now to change Solarus joystick support, to make it like we have on Retroarch, and add Rumble :)
When it will be done, it will help me to fix Joystick here too.
I'm not obsessed, but it is easier to play with it for children, they don't use Keyboard :(

**Comment by zerojay** [comment]
> For music support, you need to define USE_MODPLUG in the Makefile and the Modplug library (http://modplug-xmms.sourceforge.net/). This library needs to be patched to support looping tracks, otherwise half of the level will be silent. Alternatively, the xmp library (http://xmp.sourceforge.net/) may be used, then define USE_XMP in the Makefile. This does not need patching.

**Comment by Darknior** [comment]
Yes it's what i read on an old tutorial with an other OJ version.
I must try it to see if it works fine or not.

**Comment by Darknior** [comment]
I have test and it's COOL !!! Now we have music with loop :D 

`$ apt-cache show libxmp4`

> Package: libxmp4
> Source: libxmp
> Version: 4.3.0-1
> Architecture: armhf

`$ sudo apt-get install libxmp-dev`

And make the game like before.
But think to remove the MODPLUG to the makefile or it will crash the MAKE.
I have made a Pull Request for this.

https://github.com/AlisterT/openjazz/pull/19

**Comment by carstene1ns** [comment]
Question is, are there some specific flags for RPi needed, as the generic Makefile is just for getting it to compile a basic, native version. Other ports have specific needs (like fullscreen-only or fixed resolutions).

**Comment by Darknior** [comment]
For us FULL SCREEN and XMP sound are best options.
I know some make file testing we are on linux with ARM proc to know we are on PI.

**Comment by Darknior** [comment]
There is an exemple here but with CMAKE :(

**Comment by zerojay** [comment]
OpenJazz has been submitted.

**Comment by zerojay** [comment]
I've added the libxmp-dev dependency so music is now looping properly. Thanks.
