### ISSUE TITLE
Kodi-extra installation fails due to missing kodi-joypads repository

### ISSUE THREAD

**Issue by omgmog** [zerojay/RetroPie-Extra#272]
It looks as if @HerbFargus has deleted or made private the `kodi-joypads`  repository, so the `kodi-extra` script fails when trying to [clone the keymaps](https://github.com/zerojay/RetroPie-Extra/blob/master/scriptmodules/ports/kodi-extra.sh#L55) as part of this installation. 

Log output:
```
pi@retropie:~ $ zcat ~/RetroPie-Setup/logs/rps_2018-01-18_221754.log.gz | tail -f
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/HerbFargus/kodi-joypads.git/'
cp: cannot stat ‘keymaps/keymaps/’: No such file or directory
rm: cannot remove ‘keymaps’: No such file or directory
chown: cannot access ‘/home/pi/.kodi/userdata/keymaps’: No such file or directory
/home/pi
Error running 'git clone --recursive --depth 1 https://github.com/HerbFargus/kodi-joypads.git keymaps' - returned 128

Log ended at: Thu 18 Jan 22:26:56 UTC 2018
Total running time: 0 hours, 9 mins, 2 secs
```

**Comment by HerbFargus** [comment]
@zerojay I don't see the value in predefined joypad configs anymore especially considering the native support in Kodi for joypad configuring joypads along with the added complication of similar vendor names with different layouts, it is probably more prudent to just let the user configure things for their own set up. tbh I don't really see the value in a script to install kodi when it's integrated in the main retropie script already, the only value this module provides is to set kodi up as it's own menu in the setup script. If we just want a basic script to set up kodi as it's own system in ES we can probably modify this script to fill that function.

**Comment by omgmog** [comment]
It should be enough to install the `kodi-peripheral-joystick` package with apt

**Comment by zerojay** [comment]
Give it a shot and let me know.
