### ISSUE TITLE
Chromium error retropie 4.2

### ISSUE THREAD

**Issue by carlosricardocm** [zerojay/RetroPie-Extra#274]
Hi.

I try to install chromium but the script gave me the following error:

Could not install packages: libgnome-keyring-common libgnome-keyring0 libnss3 xdg-utils matchbox xserver-xorg-legacy xorg gconf-service libgconf-2-4

Any thoughts? 

Thanks,
PD it could be possible Update the chromium version to the one which include the widevine dmr?

**Comment by symbios24** [comment]
Hi, do an apt-get update / upgrade before and try again or try in Retropie 4.3

**Comment by carlosricardocm** [comment]
Hi, 
The instalation works, but fails when I try to launch it from the port menu inside emulastation.

**Comment by symbios24** [comment]
Quit with f4 to command line and type sudo dkpg-reconfigure xserver-xorg-legacy select anybody and press ok, reboot the os and try again

**Comment by carlosricardocm** [comment]
Hi, 

It works now, sorry for not read before hand the instructions.
I try to play somenthing in netflix but fails because the version installed of chronium is not compatible with this version of chronium, so there is a chance you could upgrade it? o maybe give me a starting point for I can make it. 
I read this guide where there is a netflix's
Chronium compatible version but I dont know how to integrate it in retropie.
https://techwiztime.com/article/netflix-on-raspberry-pi/ 
Thanks

**Comment by symbios24** [comment]
i havent try this chrome version for netflix, please try this,quit to command line again and type sudo apt get update && sudo apt-get install rpi-chromium-mods and try netflix again after.

if it does not work do what the article says, quit to command line and type

wget https://github.com/kusti8/chromium-build/releases/download/netflix-1.0.0/chromium-browser_56.0.2924.84-0ubuntu0.14.04.1.1011.deb

after type

sudo dpkg -i chromium-browser_56.0.2924.84-0ubuntu0.14.04.1.1011.deb

reboot and run chrome from ports

**Comment by symbios24** [comment]
i havent try this chrome version for netflix, please try this,quit to command line again and type sudo apt-get update && sudo apt-get install rpi-chromium-mods and try netflix again after.

if it does not work do what the article says, quit to command line and type

wget https://github.com/kusti8/chromium-build/releases/download/netflix-1.0.0/chromium-browser_56.0.2924.84-0ubuntu0.14.04.1.1011.deb

after type

sudo dpkg -i chromium-browser_56.0.2924.84-0ubuntu0.14.04.1.1011.deb

reboot and run chrome from ports

**Comment by symbios24** [comment]
Did you make it carlos?

**Comment by carlosricardocm** [comment]
Hi,
No, it doesn't work,  I don't know what's the problem because the version of chrome seems to be right and everything seems ok, but chromium keeps sending me an error when I try to play a netflix video. I install chromium with the deb package and like the video said I restarted the raspberry pi many times but the error still.
Any thoughts?
I'm going to try delete the previous chromium (the one that is installed with your script) and install only the chronium with the deb, but I don't know if this is going to be a problem when I try to lunch it from the retropie menu. 
Thanks
Ricardo

**Comment by symbios24** [comment]
What is the error message about?

**Comment by symbios24** [comment]
What is the error message about? what does it says?

i`m not the creator of this script/s just a helping hand :)

**Comment by symbios24** [comment]
you make it or not?

**Comment by carlosricardocm** [comment]
Hi, symbios I couldn't do it.

**Comment by zerojay** [comment]
Feel free to keep discussing here, but it looks like there's nothing for me to do on this.
