### ISSUE TITLE
Kweb downgrade issue

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#275]
Hello, there is a newer version of kweb and if i update it manual and after run the kweb script to check for update it downgrades kweb to the old version, as i saw from inside the script its configured to install only version 1.6.9,can you fix this so it always take an updated version if there is and not keep installing the old one?

Thanks

**Comment by zerojay** [comment]
Give me the info for the updated kweb version and I'll see what I can do.

**Comment by symbios24** [comment]
i just did a sudo upgrade after i installed kweb from the script and installed the latest version so maybe you can put that in the script

**Comment by zerojay** [comment]
I've updated kweb a few minutes ago to latest. It's rather old now so I still think Chromium is a far better option at this point. It does work however.
