### ISSUE TITLE
Crispy DOOM will not compile. 

### ISSUE THREAD

**Issue by XD3l** [zerojay/RetroPie-Extra#276]
Retropie is fully and freshly updated and I am getting this message when compiling:

COuld not successfully build crispy-doom - Crispy Doom - Enhanced port of (blah blah blah)

(/home/pi/RetroPie-Setup/tmp/build/crispy-doom/src/crispy-doom not found).

**Comment by XD3l** [comment]
Sorry, it has been FOREVER since I've dove into all of this. What is the
command to run your Crispy script by hand again? If I recall correctly,
that is how I went about getting a lot proper last time.

Do not let your theoretically benevolent care takers delude you into naive
faith. - Jordan Peterson

**Comment by symbios24** [comment]
Install Chocolate doom is way better and faster.

**Comment by XD3l** [comment]
Thank you for your opinion, but I'd still like to know the command to run
the Crispy DOOM install script individually so that I can provide Zero with
the log he needs.

Do not let your theoretically benevolent care takers delude you into naive
faith. - Jordan Peterson

**Comment by symbios24** [comment]
good luck with that

**Comment by symbios24** [comment]
good luck with that the command to run the script manual is sh crispy-doom.sh

**Comment by symbios24** [comment]
good luck with that the command to run the script manual is sh crispy-doom.sh

you can compile it your self like this:

sudo apt-get install build-essential automake
sudo apt-get build-dep chocolate-doom

cd crispy-doom
autoreconf -vif
./configure
make

i forgot to mention crispy doom has merged with chocolate doom

**Comment by XD3l** [comment]
sh crispy-doom.sh yields nothing from within the Retropie-Setup folder.

Chocolate compiles and runs fine... but has zero Crispy config options, so
I'm confused about the two being merged...

Do not let your theoretically benevolent care takers delude you into naive
faith. - Jordan Peterson

**Comment by XD3l** [comment]
Turns out it compiles fine with the old apt-get command. Must be the script
itself.

Do not let your theoretically benevolent care takers delude you into naive
faith. - Jordan Peterson

**Comment by zerojay** [comment]
Crispy Doom is a fork off of Chocolate Doom.

Chocolate Doom recently made the jump from SDL1 to SDL2 and as such, so did Crispy Doom. This could have been fixed a long time ago if anyone posted the compilation logs as previously asked.
