### ISSUE TITLE
Xserver-xorg-legacy

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#278]
Hi, xserver-xorg-legacy package is conflicting with raspbian desktop: https://github.com/RetroPie/RetroPie-Setup/issues/2299

so if removed chromium browser firefox and a bunch of other software is not working can you fix that sometime soon?

**Comment by zerojay** [comment]
I'll look into it when I can.

**Comment by zerojay** [comment]
I think this is one of those things where I'll have to separate stretch from jessie for each package that uses xserver-xorg-legacy.

**Comment by zerojay** [comment]
Chromium should be fixed now.

**Comment by zerojay** [comment]
All ports that used this have now had it removed.

**Comment by symbios24** [comment]
but without it they wont work

**Comment by zerojay** [comment]
They work.

**Comment by amo13** [comment]
Firefox-esr does not launch without it. Unfortunately, even if I install it manually, it is automatically removed when going into the retropie setup... Any clues?
