### ISSUE TITLE
Bezel Support

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#283]
Hi, can you add to your script the support for bezel packs with this script?

https://github.com/thebezelproject/BezelProject

Thanks

**Comment by zerojay** [comment]
Yeah, I'm taking a look at it right now. Even found something to fix on Github.

**Comment by zerojay** [comment]
The script just pulls down the latest bezelproject.sh from their git and places it into retropiemenu for you. Everything else needs to be done in that script. But that should be all you need to do.
