### ISSUE TITLE
Freesynd Run Aborted on retropie 4.4

### ISSUE THREAD

**Issue by nibio74** [zerojay/RetroPie-Extra#287]
Retropie 4.4 - Raspberry pi3 b +
By launching the game, I return this error (runcommand.log):

Parameters:
Executing: /opt/retropie/ports/freesynd/freesynd
Loaded 1802 sprites from hspr-0.dat
loaded 10486 frame elements
loaded 8948 frames
index contains 1970 animations
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1006: 24042 Aborted
               /opt/retropie/ports/freesynd/freesynd

**Comment by symbios24** [comment]
it looks like you did not put the correct original game files in the ports/freesynd.

**Comment by symbios24** [comment]
it looks like you did not put the correct original game files in the ports/freesynd. or you did not put the game files at all

**Comment by nibio74** [comment]
There is a parameter that allows to bypass the control of the "originality" of the files, also because not all versions (even if original) are compatible with this port, however, from the log it is clear that it loads something, but in the end it blocks everything.

**Comment by nibio74** [comment]
Can you add the file size too? Because I think I have 1 or more corrupt files since I have them all but the port does not work anyway. Thanks.

**Comment by nibio74** [comment]
Everything ok, now it works. Thank you.
