### ISSUE TITLE
Rocksndiamonds aborted run on retropie 4.4

### ISSUE THREAD

**Issue by nibio74** [zerojay/RetroPie-Extra#292]
Retropie 4.4 on raspberry pi3 b+

Runcommand.log:

Parameters:
Executing: /opt/retropie/ports/rocksndiamonds/rocksndiamonds
rocksndiamonds: warning: no game controller base mappings found
rocksndiamonds: fatal error: LoadCustomImage(): cannot find file 'RocksFontSmall
.png'
rocksndiamonds: aborting

**Comment by symbios24** [comment]
you need to put the original game files in opt/retropie/ports for the game to work

**Comment by nibio74** [comment]
Should not the game be automatically installed in the correct directory?

**Comment by nibio74** [comment]
same error. I copied all the content from /opt/retropie/ports/rocksndiamonds in /home/pi/RetroPie/roms/ports/rocksndiamonds but the result is the same.

**Comment by nibio74** [comment]
I confirm. You must copy the directories: conf, docs, graphics, levels, music and sounds from the installation file to /opt/retropie/ports/rocksndiamonds directory. Thanks.

**Comment by zerojay** [comment]
Closing this as this is something I cannot help with.
