### ISSUE TITLE
[Request] lr-FreeJ2ME

### ISSUE THREAD

**Issue by SuperFromND** [zerojay/RetroPie-Extra#296]
**Repository:** https://github.com/hex007/freej2me
Requires Apache Ant to compile and Java to run since it uses .jar files.

This theoretically shouldn't be *too* hard to convert into a shell script, however I was never able to successfully compile from source.  Then again, I haven't tried it since before I upgraded to RetroPie 4.4, so maybe something's changed...

**Comment by zerojay** [comment]
That's going to probably end up being a hell of a lot of dependencies and Java is just hell, but as someone who worked on some of these games... I have an interest. I'll see what I can do.

**Comment by zerojay** [comment]
Added lr-freej2me libretrocore. Working well for me.
