### ISSUE TITLE
creating ports

### ISSUE THREAD

**Issue by symbios24** [zerojay/RetroPie-Extra#304]
Hi, i managed to create an install script for a port for simutrans game

the thing is the game upon run after a minute it stuck/hang and i have to remove the power

if i put the command xinit in the script eg ""xinit /usr/games/simutrans"
it works perfect but the resolution is smaller in a windows in the middle is that normal?  
can the resolution be normal with the xinit command?
i`m planning to do many ports in scripts but how do i know if a game needs the xinit or not?
do i put xinit to every game?

thanks

**Comment by zerojay** [comment]
When it comes to whether or not you know if a game requires xinit or not, it's more or less trial and error, to be honest with you. In cases where a game doesn't go fullscreen, it's possible to try different resolutions through runcommand until you find one that fits... or the other option is to try including a window manager such as matchbox. There are a few ports in the repo that use matchbox and request a full screen window, so you should be able to find examples. I think the Theme Hospital clone uses it.

**Comment by zerojay** [comment]
Sorry, misspoke. Looks like Chromium, weechat, deadbeef and a few others use matchbox, not the Theme Hospital clone.

**Comment by symbios24** [comment]
nevermind i figured it out

**Comment by zerojay** [comment]
I'm going to try a port for simultrans soon.
