### ISSUE TITLE
Chromium not launching 

### ISSUE THREAD

**Issue by andlill** [zerojay/RetroPie-Extra#314]
Hi 

I've just installed the Chromium port on a fresh Retro pie 4.6 prebuilt image (Buster) and the browser do not start, any thoughts on this ?

Do you need and/or want any fault logs ?

**Comment by zerojay** [comment]
Hi, please read the note at the top of the repository's Readme.md. There is zero expectation that anything in this Github repository works anymore. It only exists as an archive of the work I had done and should no longer be used in any way, shape or form.

**Comment by ArrowRaider** [comment]
Such a note does not exist in the readme and Chromium doesn't work after install. Archive this repo if it is dead.
