### ISSUE TITLE
SorR folder reverts every time there is and update.

### ISSUE THREAD

**Issue by UtamaruMonster** [zerojay/RetroPie-Extra#317]
Good day. 

Will start with thanking you for creating the possibility for us to play Streets of rage Remake 🙇  . 

This is probably a question and not an issue. 

I have retropie v4.6 RPi4. I have install SorR in `/opt/retropie/ports/sorr` with `bagdi-333` and a special `emulators.cfg`. But every time there is an update this folder (`sorr`) is wiped clean and returned to it's original state with `bgdi-330`. Is there any way to stop this?

Thank you.

**Comment by zerojay** [comment]
I'll give this a try and attempt to reproduce it. 

"But everytime there is an update..."
An update to what, exactly?

**Comment by UtamaruMonster** [comment]
Sorry for the late response. Retropie update, system update or just install Kodi. When i do any of those

**Comment by zerojay** [comment]
I just saw this happen to me for the first time a few minutes ago. I am utterly baffled as to why this is happening. Taking a deeper look into it.

**Comment by zerojay** [comment]
This also just happened with my openxcom script. I'm very confused. I've opened a question about it on the Retropie forums.
