### ISSUE TITLE
Rise of the triad crashes before it starts

### ISSUE THREAD

**Issue by TheOneAnthony** [zerojay/RetroPie-Extra#318]
when trying to run it, the whole program freezes before it even loads. i tried loading its executable directly through the terminal. at first i used  ./rott-shareware and it said could not initialize SDL. 
adding sudo made it say could not change video mode.
//////////////////////////////////////////////////////////////////copy of terminal
./rott-shareware
////////////////////////////////////////////////////////////////////
Rise of the Triad Startup  Version 1.4
 Shareware Version
Z_INIT: 8950000 bytes
IN_Startup: Mouse Present
    Adding /home/pi/RetroPie/roms/ports/rott/shareware/huntbgin.wad.
    Adding /home/pi/RetroPie/roms/ports/rott/shareware/remote1.rts.
W_Wad: Wad Manager Started NUMLUMPS=2103
RT_DRAW: Tables Initialized
MU_Startup:
SD_SetupFXCard: Fx ok.
SD_Startup: Fx ok.
RT_MAIN: Fonts Initialized
RT_MSG: Message System Started
RT_VIEW: Colormaps Initialized
Could not initialize SDL Episode      = 0
Area         = 1

//////////////////////////////////////////////////////////// copy of terminal
sudo ./rott-shareware
///////////////////////////////////////////////////////////////
RT_DRAW: Tables Initialized
MU_Startup:
SD_SetupFXCard: Fx ok.
SD_Startup: Fx ok.
RT_MAIN: Fonts Initialized
RT_MSG: Message System Started
RT_VIEW: Colormaps Initialized
Could not set video mode Episode      = 0
Area         = 1
pi@retropie:/opt/retropie

**Comment by TheOneAnthony** [comment]
I managed to fix it the error was below 
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/TimGM6mb.sf2"
i looke din that folder and there was an sf2 file but under a different name. i copied it and renamed the copy to that of the missing file. it worked perfectly and the game booted up. 

do you know if contorllers work? i cant seem to get it to.

**Comment by zerojay** [comment]
I'll try to look into the crash. As for controllers, I am not sure.

**Comment by TheOneAnthony** [comment]
the crash was because i was missing timgm6mb.sf2 in the sound-font folder. manually adding it seemed to fix it.

**Comment by zerojay** [comment]
OK, so that sounds like it's not really an issue with the installer script then, it's just data that the user is supposed to provide by the sounds of it.

**Comment by TheOneAnthony** [comment]
I would work that file into the script anyway. The only reason I found that
out was because I looked at the runcommand log and there was no mention of
this anywhere else. Including the readme.

**Comment by zerojay** [comment]
Keeping this open during investigation.

**Comment by zerojay** [comment]
In looking deeper into this issue, I do not have a /usr/share/sounds/sf2 folder on my pi whatsoever and it was not stopping the game from launching. The problem I was having was that the shareware data files were not copied where they should be and were not capitalized as the game is expecting them. I made a submit to fix those issues and the game is running perfectly fine for me now (with the exception of being just in the top left corner of the screen).
