### ISSUE TITLE
Ports Correction

### ISSUE THREAD

**Issue by actraiser30** [zerojay/RetroPie-Extra#319]
Hello there welcome back i have made a few correction to some scripts so they work or just update them to the latest versions

freesynd please update it to version 0.7.5 it works fine

openxcom replace the sources of glshim.git  with the sources of gl4es to work

manaplus add autopoint to depends

chocolate doom update in the script freedoom to v0.12.1

and some other that i will write them in time

**Comment by zerojay** [comment]
It would be great for future corrections to please make them each their own issue. It's a lot easier for me to track that way. Thanks, I appreciate the info.

**Comment by zerojay** [comment]
> openxcom replace the sources of glshim.git with the sources of gl4es to work

gl4es is the same as glshim, the repository was just renamed.

**Comment by actraiser30** [comment]
Strange i had the feeling its working better like that

Στις Τρί, 15 Σεπ 2020, 19:38 ο χρήστης zerojay <notifications@github.com>
έγραψε:

**Comment by zerojay** [comment]
freesynd has been bumped and has had a dependency updated.

**Comment by zerojay** [comment]
Manaplus needed autopoint added, libpng12-dev changed to libpng-dev and to be run under sudo xinit, not just xinit. Resolution still needs to be fixed as it's only on 1/4th of the screen.

**Comment by zerojay** [comment]
Chocolate Doom dependencies for libpng12-dev and python-imaging replaced with libpng-dev and python-pil to fix compilation. Bumped freedoom to 0.12.1.

**Comment by zerojay** [comment]
Openxcom updated.
