### ISSUE TITLE
Preliminary Ishiiruka port needs gtk2 and wxwidgets dependencies

### ISSUE THREAD

**Issue by burt111** [zerojay/RetroPie-Extra#325]
I modified the dolphin script to work with ishiiruka only way for me to find the WX widgets libraries and gtk2 libraries is to install dolphin emu and then uninstall I don't know if you want to use this script in your experimental ports section should require minimal modification to work with the dependencies

**Comment by burt111** [comment]
#
[dolphin.log](https://github.com/zerojay/RetroPie-Extra/files/5291978/dolphin.log)

**Comment by zerojay** [comment]
This repo is mainly aimed at stuff that is functional for the Raspberry Pi, so I don't feel that it's approrpriate here as I will have no way to maintain it later if things break.
