### ISSUE TITLE
SORR Error on instalation

### ISSUE THREAD

**Issue by krahsdevil** [zerojay/RetroPie-Extra#326]
Hi.
I'm getting this error on SORR instalation (Retropie 4.6, Buster):
`Could not install package(s): libpng.`
I've checked the script and looks like that recently this line:
`getDepends libsdl-mixer1.2 libpng12-0`
was changed by this one:
`getDepends libsdl-mixer1.2 libpng libpng-dev`

If I revert this change in the script then no issues and libpng12-0 is installed, making SORR works fine (it's requirred) once you copy all the needed files at its roms folder.

Thanks!

**Comment by zerojay** [comment]
Can you try with the following instead?
getDepends libsdl-mixer1.2 libpng-dev

**Comment by zerojay** [comment]
I've submitted a fix. If it doesn't work for you, please feel free to reopen.
