### ISSUE TITLE
SORR Reopen issue #326

### ISSUE THREAD

**Issue by krahsdevil** [zerojay/RetroPie-Extra#327]
Hi!
Sorry for the delay, I've tested the installation script with the modification.
Now I don't get the error and it ends as expected but, when you launch SORR you get this error on runcommand.log:

`Parameters: 
Executing: pushd /opt/retropie/ports/sorr; ./bgdi-333 ./SorR.dat; popd
/opt/retropie/ports/sorr ~
./bgdi-333: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
~`

Game has a dependency to libpng12-0, so if I install it manually game launch perfectly:

`sudo apt-get install libpng12-0`

This line seems to do the trick: `getDepends libsdl-mixer1.2 libpng12-0`

There is any reason you change it by `getDepends libsdl-mixer1.2 libpng-dev`?

Thanks!

**Comment by zerojay** [comment]
Fixed.
