### ISSUE TITLE
Control web browser (chromium/firefox/kweb) with gamepad

### ISSUE THREAD

**Issue by amo13** [zerojay/RetroPie-Extra#346]
Thank you a lot for your script and this repository!

I wonder if anybody can think of a way to control firefox or chromium with the gamepad? I use a xbox360 controller, but simply starting xboxdrv with the --mouse flag over ssh while running firefox unfortunately does not work and breaks the controller in emulationstation afterwards. I have to reboot to make the controller work again in emulationstation.

Any idea would be greatly appreciated!

**Comment by veogehog** [comment]
I too am very thankful for the repository but would also absolutely love it if we could map a controller to a mouse, or keyboard even.

I could see this working with the d-pad mapped to the mouse and simple right click and left click mapped to buttons 1 and 2

Or maybe the controller mapped to a keyboard and using the TAB key a lot (not ideal but at least makes the controller usable for things like Netflix)

**Comment by zerojay** [comment]
This is outside of the scope of the repo. It would probably be best to take this up on the forum.
