### ISSUE TITLE
EasyRPGMaker fails on install

### ISSUE THREAD

**Issue by oakbrad** [zerojay/RetroPie-Extra#347]
I've flashed the most recent RetroPie onto a Pi0 but am unable to install the EasyRPGMaker from this script.

Fails on "Could not install package(s): libsdl2-mixer-dev libpng12-dev libboost-dev."

Anyone have any insight? Would love to get this running.

**Comment by symbios24** [comment]
Install the packages manual and after install the rpg maker

**Comment by zerojay** [comment]
This repo is not intended for use on a Pi0. If you are not on Pi3/Pi4 with latest OS, all bets are off.
