### ISSUE TITLE
Hexen: Deathkings of the Dark Citadel?

### ISSUE THREAD

**Issue by davidj1987** [zerojay/RetroPie-Extra#35]
Just wondering if the Chocolate Doom script can be updated to add this. It was the extension to Hexen.

**Comment by zerojay** [comment]
This should be doable.

**Comment by davidj1987** [comment]
Wow, that was quick, I just got it working on my end, my way may be a bit messier but working. Just copied the chocolate-hexen folder, added the commandline to load the addon, renamed the folder and copied the script file in the Roms folder and changed it to reflect the renamed folder and bam got it loaded that way. Thank you!

**Comment by zerojay** [comment]
Please try to use the updated script so that we know that it is actually working properly when you can.
