### ISSUE TITLE
Repository Games List

### ISSUE THREAD

**Issue by HerbFargus** [zerojay/RetroPie-Extra#40]
Here is a games list based on `apt-cache search games`:

http://pastebin.com/UTfPhzuv

and this is a list from `apt-cache search opengl` (for future reference or at least to eliminate some of the above list)

http://pastebin.com/byUqqgHU

There are 3 main caveats that may apply to games on the list: 
- Requires X
- Requires OpenGL
- Not really a Game

Should be very easy to almost autogenerate port templates for all of them (pending launch names match package names which is not always the case) 

Not  sure if this is useful or not, but its here for those that are curious.

**Comment by zerojay** [comment]
I appreciate it. I'll take a look through it sometime soonish.

**Comment by zerojay** [comment]
Won't be automatically generating port templates, out of date list for buster.
