### ISSUE TITLE
EasyRPG Player: Could Not Successfully Build. 

### ISSUE THREAD

**Issue by XD3l** [zerojay/RetroPie-Extra#42]
Upon first attempt it failed to install:

libpixman-1-dev
libicu.dev

I tried to manually install both via apt-get, but it only allowed me to install libpixman-1-dev.

I tried the script for EasyRPG Player again. This time it made it further, but in the end said it could not build EasyRPG Player. 

checking dependency style of g++... gcc3
./configure: line 4995: syntax error near unexpected token `disable-shared'
./configure: line 4995: `LT_INIT(disable-shared)'
make: *** No targets specified and no makefile found.  Stop.
/home/pi/RetroPie-Setup
Could not successfully build EasyRPG Player - RPG Maker 2000 and 2003 Interpreter (/home/pi/RetroPie-Setup/tmp/build/easyrpgplayer/player/easyrpg-player not found).

**Comment by zerojay** [comment]
Perhaps libicu-dev failed to download causing that issue.

As far as what you see here, I wiped out my install completely and installed from scratch and there was a missing dependency upon libtool. I've updated the script to include the dependency so you should just need to update your copy of the script and try to build it again.

**Comment by zerojay** [comment]
There are other issues with this script that I'm currently working through.

**Comment by zerojay** [comment]
I've updated the script again to fix some compilation and linking fixes. Please update your copy of the repo and try it again.

**Comment by XD3l** [comment]
Bingo!

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by XD3l** [comment]
Also... I had created a complete set up guide for this on the Wiki...
...it's magically gone now.

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
Perhaps because the module isn't in mainline RetroPie. You can feel free to throw it into the wiki here. Let me know if I need to do anything to set it up for you.
