### ISSUE TITLE
Chromium: matchbox: can't open display! check your DISPLAY variable.

### ISSUE THREAD

**Issue by XD3l** [zerojay/RetroPie-Extra#43]
Chromium installs fine, but when I attempt to launch it via EmulationStation or Command line, I end up with this error:

matchbox: can't open display! check your DISPLAY variable.

**Comment by zerojay** [comment]
(Wrong bug number, please ignore the above.)

**Comment by zerojay** [comment]
Did you already have a graphical session open at the time? Usually the display variable should be :0 automatically which would point to the first graphical session open. Perhaps X never launched? Taking a look at this.

**Comment by XD3l** [comment]
The only "graphical session" that I run and am ever aware of is
EmulationStation if that is what you mean.
I never installed an X environment, unless one game with RetroPie by
default.

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
If you update the script, you should now get a warning at the end of installation warning you that you may need to give X11 permissions to the user you are running as.

The big hint that this was the problem was in /tmp/runcommand.txt, which is written every launch and may contain errors and other helpful info to debug the issue. 

Thanks for the report.

**Comment by XD3l** [comment]
I never got  aruncommand.txt

I do get this now though when trying to run it by command line...

pi@retropie:/opt/retropie/ports/chromium $ sh chromium.sh
xset:  unable to open display ""
matchbox: can't open display! check your DISPLAY variable.
/usr/bin/chromium-browser: line 138: lsb_release: command not found
/usr/bin/chromium-browser: line 139: lsb_release: command not found
/usr/lib/chromium-browser/chromium-browser: error while loading shared
libraries: libgconf-2.so.4: cannot open shared object file: No such file or
directory
pi@retropie:/opt/retropie/ports/chromium $


“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by XD3l** [comment]
I also tried the following:

sudo apt-get -f install

sudo apt-get install libgconf2-4

--

I then tried to load Chromium, but got this:

pi@retropie:/opt/retropie/ports/chromium $ sh chromium.sh
xset:  unable to open display ""
matchbox: can't open display! check your DISPLAY variable.
/usr/bin/chromium-browser: line 138: lsb_release: command not found
/usr/bin/chromium-browser: line 139: lsb_release: command not found
[1587:1587:0320/055512:ERROR:browser_main_loop.cc(256)] Gtk: cannot open
display:


“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by XD3l** [comment]
Oh wait... this now works from EmulationStation!!!

...so in theory, could not Jedi Outcast as well... ? ;)

Anyhow, not to get off subject, but I hope my error reports have helped.

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
They are helping. It's not easy to catch some of these dependencies sometimes.

**Comment by kevin007** [comment]
Good Evening,

I am having the same error, I updated the Xwrapper.config file to allow anybody but am still getting the error, can you help?

**Comment by zerojay** [comment]
Unfortunately, my Pi is dead so I can't help right now, sorry.
