### ISSUE TITLE
Kens Labyrinth?

### ISSUE THREAD

**Issue by davidj1987** [zerojay/RetroPie-Extra#54]
Here's a source port for Kens Labyrinth: https://icculus.org/LAB3D/

**Comment by zerojay** [comment]
It's OpenGL, not OpenGLES. There's a chance it will work with either the glshim or the OpenGL driver, neither of which I've gotten to work very well to this point.

**Comment by zerojay** [comment]
I attempted this through glshim and it seemed to segfault on launch each and every time as far as I saw.
