### ISSUE TITLE
CorSixth Depends

### ISSUE THREAD

**Issue by XD3l** [zerojay/RetroPie-Extra#65]
My results:

E: There are problems and -y was used without --force-yes
Could not install package(s): liblua5.2-0 liblua5.2-dev lua-filesystem lua-lpeg libavcodec-dev libavformat-dev libavresample-dev libavutil-dev libavdevice-dev libswscale-dev libpostproc-dev libavfilter-dev.

**Comment by zerojay** [comment]
Try again when the raspbian mirrordirector isn't dying left and right.

**Comment by XD3l** [comment]
Oh... how do I know when that is?

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
You're not going to know without trying. I think it's failing for you because of that. You can maybe select a specific mirror but that's beyond the scope of this bug.
