### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by HerbFargus** [zerojay/RetroPie-Extra#66]
I dont really want the retropie wiki cluttered with stuff that isnt part of retropie yet,  I think it would be good to initialise the wiki here so if @XD3l wants to do some documentation for the ports here it gives them a spot, and will make for an easy transfer when other ports are included with RetroPie.

**Comment by XD3l** [comment]
I am new to this wiki business, but if you tell me where you'd like to ad
my additions, I'll happily comply.

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
Initialized. Put it anywhere, I'll move it if I need to.

https://github.com/zerojay/RetroPie-Extra/wiki

**Comment by HerbFargus** [comment]
I've moved over EasyRPG for the time being. Thanks for your help.

**Comment by XD3l** [comment]
Thank you!

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>
