### ISSUE TITLE
Add TI-99

### ISSUE THREAD

**Issue by HerbFargus** [zerojay/RetroPie-Extra#67]
Guide for installing here:

http://atariage.com/forums/topic/250767-how-to-install-ti-994a-ti-99sim-on-retropie-v36-raspberry-pi2-or-pi3/

![image](https://cloud.githubusercontent.com/assets/10035308/14062601/5d9be3ba-f36a-11e5-9eda-3728f60762ce.png)

**Comment by zerojay** [comment]
I'll look into this soonish.

**Comment by zerojay** [comment]
Completed and added to the master branch.
