### ISSUE TITLE
Streets of Rage Remake - Unable to save.

### ISSUE THREAD

**Issue by zerojay** [zerojay/RetroPie-Extra#81]
Apparently, there are some save game issues as reported on the petrockblog site.

**Comment by zerojay** [comment]
I'm currently unable to reproduce this issue. Saves are written properly for me to /opt/retropie/configs/ports/sorr/savegame.sor. When the file is deleted, it is recreated upon quitting SORR properly.

**Comment by dishins** [comment]
Hi @zerojay, i'm the one who reported the issue @petrockblog forums, however, it was fixed after i manually deleted and recreated the file.

**Comment by zerojay** [comment]
Thank you.
